require 'opentox-client'
require 'rack'
require 'rack/contrib'
require 'sinatra'
require 'roo'
require 'rdf/n3'
#require File.join(File.dirname(__FILE__),"environment.rb")
require File.join(File.dirname(__FILE__),"4store.rb")
require File.join(File.dirname(__FILE__),"opentox.rb")
require File.join(File.dirname(__FILE__),"authorization-helper.rb")
